global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "project_service"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ['my-project-service:8081']
        labels:
          application: 'Project Service Application'